### ISSUE TITLE
Nonblocking issue: Peter is an idiot

### ISSUE THREAD

**Issue by petersulucz** [justaniles/smart-home-portal#2]
In my professional opinion, testing would be more enjoyable if more of the example names began with the letter 'P'.

**Comment by petersulucz** [comment]
Still waiting on response here...

**Comment by justaniles** [comment]
Saw this a little bit too late...all semblance of mocks and tests are now [gone](http://giphy.com/gifs/nuclear-smoke-stack-explosion-iZuLdzQ5eoD1C).

**Comment by petersulucz** [comment]
NO. NO. NO.

**Comment by petersulucz** [comment]
I know this code no longer exists. I still want it back.

**Comment by petersulucz** [comment]
I AM A COLLABORATOR. I DO WHAT I WANT

**Comment by justaniles** [comment]
This is **_done**_ (notice the **bold** **_and**_ _italics_)

**Comment by petersulucz** [comment]
It does not seem that the root cause has been addressed.

**Comment by justaniles** [comment]
Keeping mean time to close down
