### ISSUE TITLE
SEV 0: JUSTIN IS AN IDIOT

### ISSUE THREAD

**Issue by petersulucz** [justaniles/smart-home-portal#3]
Stranger things is literally scaring the crap out of me right now. 
Also. Pancake doesn't work. www.pancake.com seems broken.

**Comment by justaniles** [comment]
Keeping mean time to close down

**Comment by petersulucz** [comment]
Just tried to repo. Bug still exists.

**Comment by justaniles** [comment]
This is dumb.
